name: T04 - Only feature1

on:
  push:
    branches: [ feature1 ]   # workflow käynnistyy vain feature1 branchille

jobs:
  only-feature1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This runs ONLY on feature1"
