name: T10 - Secrets

on:
  push:
    branches: [ main ]

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret presence (safe)
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "Secret is NOT set"; exit 1
          else
            echo "Secret is set ✔"
          fi